var annotated_dup =
[
    [ "stool", null, [
      [ "beller", null, [
        [ "BellerComponent", "classstool_1_1beller_1_1BellerComponent.html", null ],
        [ "BellerSmallComponent", "structstool_1_1beller_1_1BellerSmallComponent.html", null ],
        [ "LCPEnumerator", "classstool_1_1beller_1_1LCPEnumerator.html", "classstool_1_1beller_1_1LCPEnumerator" ],
        [ "LCPInfo", "structstool_1_1beller_1_1LCPInfo.html", null ],
        [ "LCPIntervalEnumerator", "classstool_1_1beller_1_1LCPIntervalEnumerator.html", "classstool_1_1beller_1_1LCPIntervalEnumerator" ]
      ] ],
      [ "bwt", null, [
        [ "BackwardISA", "classstool_1_1bwt_1_1BackwardISA.html", "classstool_1_1bwt_1_1BackwardISA" ],
        [ "BWTFunctions", "classstool_1_1bwt_1_1BWTFunctions.html", null ],
        [ "LFDataStructure", "classstool_1_1bwt_1_1LFDataStructure.html", "classstool_1_1bwt_1_1LFDataStructure" ]
      ] ],
      [ "rlbwt2", null, [
        [ "ForwardSA", "classstool_1_1rlbwt2_1_1ForwardSA.html", null ],
        [ "FPosDataStructure", "classstool_1_1rlbwt2_1_1FPosDataStructure.html", null ],
        [ "LFDataStructureBasedOnRLBWT", "classstool_1_1rlbwt2_1_1LFDataStructureBasedOnRLBWT.html", null ],
        [ "LightFPosDataStructure", "classstool_1_1rlbwt2_1_1LightFPosDataStructure.html", null ],
        [ "RankSupportVectorWrapper", "classstool_1_1rlbwt2_1_1RankSupportVectorWrapper.html", null ],
        [ "RLE", "classstool_1_1rlbwt2_1_1RLE.html", null ],
        [ "WaveletTreeOnHeadChars", "classstool_1_1rlbwt2_1_1WaveletTreeOnHeadChars.html", null ]
      ] ],
      [ "ArrayConstructor", "classstool_1_1ArrayConstructor.html", null ],
      [ "BasicSearch", "classstool_1_1BasicSearch.html", null ],
      [ "BitDeque", "classstool_1_1BitDeque.html", "classstool_1_1BitDeque" ],
      [ "Byte", "classstool_1_1Byte.html", null ],
      [ "CharacterRun", "structstool_1_1CharacterRun.html", "structstool_1_1CharacterRun" ],
      [ "CharInterval", "classstool_1_1CharInterval.html", null ],
      [ "DebugPrinter", "classstool_1_1DebugPrinter.html", null ],
      [ "EliasFanoVector", "classstool_1_1EliasFanoVector.html", "classstool_1_1EliasFanoVector" ],
      [ "EliasFanoVectorBuilder", "classstool_1_1EliasFanoVectorBuilder.html", "classstool_1_1EliasFanoVectorBuilder" ],
      [ "EqualChecker", "classstool_1_1EqualChecker.html", null ],
      [ "FileWriter", "classstool_1_1FileWriter.html", null ],
      [ "ForwardRLE", "classstool_1_1ForwardRLE.html", "classstool_1_1ForwardRLE" ],
      [ "IntegerDeque", "classstool_1_1IntegerDeque.html", "classstool_1_1IntegerDeque" ],
      [ "IntervalSearchDataStructure", "classstool_1_1IntervalSearchDataStructure.html", null ],
      [ "IO", "classstool_1_1IO.html", null ],
      [ "LCPInterval", "classstool_1_1LCPInterval.html", "classstool_1_1LCPInterval" ],
      [ "LCPIntervalDepthOrderComp", "structstool_1_1LCPIntervalDepthOrderComp.html", "structstool_1_1LCPIntervalDepthOrderComp" ],
      [ "LCPIntervalPreorderComp", "structstool_1_1LCPIntervalPreorderComp.html", "structstool_1_1LCPIntervalPreorderComp" ],
      [ "LCPIntervalSort", "classstool_1_1LCPIntervalSort.html", null ],
      [ "Log", "classstool_1_1Log.html", null ],
      [ "LSBByte", "classstool_1_1LSBByte.html", null ],
      [ "LZFactor", "structstool_1_1LZFactor.html", "structstool_1_1LZFactor" ],
      [ "Memory", "classstool_1_1Memory.html", null ],
      [ "Message", "classstool_1_1Message.html", null ],
      [ "MSBByte", "classstool_1_1MSBByte.html", null ],
      [ "NaiveDynamicString", "classstool_1_1NaiveDynamicString.html", "classstool_1_1NaiveDynamicString" ],
      [ "OnlineFileReader", "classstool_1_1OnlineFileReader.html", "classstool_1_1OnlineFileReader" ],
      [ "Printer", "classstool_1_1Printer.html", null ],
      [ "Rational", "structstool_1_1Rational.html", "structstool_1_1Rational" ],
      [ "RLEIO", "classstool_1_1RLEIO.html", null ],
      [ "RMQSmallSparseTable", "classstool_1_1RMQSmallSparseTable.html", "classstool_1_1RMQSmallSparseTable" ],
      [ "RMQSparseTable", "classstool_1_1RMQSparseTable.html", "classstool_1_1RMQSparseTable" ],
      [ "ShortBitVector", "classstool_1_1ShortBitVector.html", null ],
      [ "ShortEliasFanoVector", "classstool_1_1ShortEliasFanoVector.html", "classstool_1_1ShortEliasFanoVector" ],
      [ "ShortIntegerVector", "classstool_1_1ShortIntegerVector.html", null ],
      [ "SimpleDeque", "classstool_1_1SimpleDeque.html", "classstool_1_1SimpleDeque" ],
      [ "SimpleSuffixTree", "classstool_1_1SimpleSuffixTree.html", "classstool_1_1SimpleSuffixTree" ],
      [ "SortString", "classstool_1_1SortString.html", null ],
      [ "StringFunctions", "classstool_1_1StringFunctions.html", null ],
      [ "StringFunctionsOnSA", "classstool_1_1StringFunctionsOnSA.html", null ],
      [ "StringGenerator", "classstool_1_1StringGenerator.html", null ],
      [ "SubstringComplexityFunctions", "classstool_1_1SubstringComplexityFunctions.html", null ],
      [ "TextStatistics", "structstool_1_1TextStatistics.html", "structstool_1_1TextStatistics" ],
      [ "UInt8VectorGenerator", "classstool_1_1UInt8VectorGenerator.html", null ],
      [ "ValueArray", "classstool_1_1ValueArray.html", "classstool_1_1ValueArray" ],
      [ "VLCDeque", "classstool_1_1VLCDeque.html", "classstool_1_1VLCDeque" ]
    ] ]
];