var hierarchy =
[
    [ "stool::ArrayConstructor", "classstool_1_1ArrayConstructor.html", null ],
    [ "stool::bwt::BackwardISA< LF_DATA_STRUCTURE >", "classstool_1_1bwt_1_1BackwardISA.html", null ],
    [ "stool::BasicSearch", "classstool_1_1BasicSearch.html", null ],
    [ "stool::beller::BellerComponent", "classstool_1_1beller_1_1BellerComponent.html", null ],
    [ "stool::beller::BellerSmallComponent", "structstool_1_1beller_1_1BellerSmallComponent.html", null ],
    [ "stool::BitArrayDeque< MAX_BIT_LENGTH >", "classstool_1_1BitArrayDeque.html", null ],
    [ "stool::BitArrayDeque< MAX_BIT_LENGTH >::BitArrayDequeIterator", "classstool_1_1BitArrayDeque_1_1BitArrayDequeIterator.html", null ],
    [ "stool::bwt::BWTFunctions", "classstool_1_1bwt_1_1BWTFunctions.html", null ],
    [ "stool::Byte", "classstool_1_1Byte.html", null ],
    [ "stool::ByteArrayDeque< INDEX_TYPE >", "classstool_1_1ByteArrayDeque.html", null ],
    [ "stool::ByteArrayDeque< INDEX_TYPE >::ByteArrayDequeIterator", "classstool_1_1ByteArrayDeque_1_1ByteArrayDequeIterator.html", null ],
    [ "stool::CharacterRun< CHAR, INDEX >", "structstool_1_1CharacterRun.html", null ],
    [ "stool::CharInterval< INDEX, CHAR >", "classstool_1_1CharInterval.html", null ],
    [ "stool::CircularBitPointer", "structstool_1_1CircularBitPointer.html", null ],
    [ "stool::CircularBytePointer", "structstool_1_1CircularBytePointer.html", null ],
    [ "stool::DebugPrinter", "classstool_1_1DebugPrinter.html", null ],
    [ "stool::EliasFanoVector", "classstool_1_1EliasFanoVector.html", null ],
    [ "stool::EliasFanoVectorBuilder", "classstool_1_1EliasFanoVectorBuilder.html", null ],
    [ "stool::EqualChecker", "classstool_1_1EqualChecker.html", null ],
    [ "stool::FasterStaticArrayDeque< MAX_ELEMENT_COUNT >", "classstool_1_1FasterStaticArrayDeque.html", null ],
    [ "stool::FasterStaticArrayDeque< MAX_ELEMENT_COUNT >::FasterStaticArrayDequeIterator", "classstool_1_1FasterStaticArrayDeque_1_1FasterStaticArrayDequeIterator.html", null ],
    [ "stool::FileWriter", "classstool_1_1FileWriter.html", null ],
    [ "stool::ForwardRLE< TEXT_ITERATOR_BEGIN, TEXT_ITERATOR_END, CHAR >", "classstool_1_1ForwardRLE.html", null ],
    [ "stool::ForwardRLE< TEXT_ITERATOR_BEGIN, TEXT_ITERATOR_END, CHAR >::ForwardRLEIterator", "classstool_1_1ForwardRLE_1_1ForwardRLEIterator.html", null ],
    [ "stool::rlbwt2::ForwardSA", "classstool_1_1rlbwt2_1_1ForwardSA.html", null ],
    [ "stool::rlbwt2::FPosDataStructure", "classstool_1_1rlbwt2_1_1FPosDataStructure.html", null ],
    [ "stool::IntegerArrayDeque< T >", "classstool_1_1IntegerArrayDeque.html", null ],
    [ "stool::IntegerDeque< INDEX_TYPE >", "classstool_1_1IntegerDeque.html", null ],
    [ "stool::IntegerArrayDeque< T >::IntegerDequeIterator", "classstool_1_1IntegerArrayDeque_1_1IntegerDequeIterator.html", null ],
    [ "stool::IntegerDeque< INDEX_TYPE >::IntegerDequeIterator", "classstool_1_1IntegerDeque_1_1IntegerDequeIterator.html", null ],
    [ "stool::IntervalSearchDataStructure< CHAR >", "classstool_1_1IntervalSearchDataStructure.html", null ],
    [ "stool::IntervalSearchDataStructure< uint8_t >", "classstool_1_1IntervalSearchDataStructure.html", null ],
    [ "stool::IO", "classstool_1_1IO.html", null ],
    [ "stool::bwt::BackwardISA< LF_DATA_STRUCTURE >::iterator", "classstool_1_1bwt_1_1BackwardISA_1_1iterator.html", null ],
    [ "stool::EliasFanoVector::iterator", "classstool_1_1EliasFanoVector_1_1iterator.html", null ],
    [ "stool::ShortEliasFanoVector::iterator", "classstool_1_1ShortEliasFanoVector_1_1iterator.html", null ],
    [ "stool::beller::LCPEnumerator", "classstool_1_1beller_1_1LCPEnumerator.html", null ],
    [ "stool::beller::LCPInfo", "structstool_1_1beller_1_1LCPInfo.html", null ],
    [ "stool::LCPInterval< index_type >", "classstool_1_1LCPInterval.html", null ],
    [ "stool::LCPInterval< INDEX >", "classstool_1_1LCPInterval.html", null ],
    [ "stool::LCPIntervalDepthOrderComp< INDEX >", "structstool_1_1LCPIntervalDepthOrderComp.html", null ],
    [ "stool::beller::LCPIntervalEnumerator", "classstool_1_1beller_1_1LCPIntervalEnumerator.html", null ],
    [ "stool::beller::LCPIntervalEnumerator::LCPIntervalIterator", "classstool_1_1beller_1_1LCPIntervalEnumerator_1_1LCPIntervalIterator.html", null ],
    [ "stool::LCPIntervalPreorderComp< INDEX >", "structstool_1_1LCPIntervalPreorderComp.html", null ],
    [ "stool::LCPIntervalSort", "classstool_1_1LCPIntervalSort.html", null ],
    [ "stool::beller::LCPEnumerator::LCPIterator", "classstool_1_1beller_1_1LCPEnumerator_1_1LCPIterator.html", null ],
    [ "stool::bwt::LFDataStructure", "classstool_1_1bwt_1_1LFDataStructure.html", null ],
    [ "stool::rlbwt2::LFDataStructureBasedOnRLBWT< RLBWT, FPOS_TYPE >", "classstool_1_1rlbwt2_1_1LFDataStructureBasedOnRLBWT.html", null ],
    [ "stool::rlbwt2::LightFPosDataStructure", "classstool_1_1rlbwt2_1_1LightFPosDataStructure.html", null ],
    [ "stool::Log", "classstool_1_1Log.html", null ],
    [ "stool::LSBByte", "classstool_1_1LSBByte.html", null ],
    [ "stool::LZFactor", "structstool_1_1LZFactor.html", null ],
    [ "stool::Memory", "classstool_1_1Memory.html", null ],
    [ "stool::Message", "classstool_1_1Message.html", null ],
    [ "stool::MSBByte", "classstool_1_1MSBByte.html", null ],
    [ "stool::NaiveArray< SIZE >", "classstool_1_1NaiveArray.html", null ],
    [ "stool::NaiveBitVector< MAX_BIT_LENGTH >", "classstool_1_1NaiveBitVector.html", null ],
    [ "stool::NaiveBitVector< MAX_BIT_LENGTH >", "classstool_1_1NaiveBitVector.html", null ],
    [ "stool::NaiveBitVector< MAX_BIT_LENGTH >::NaiveBitVectorIterator", "classstool_1_1NaiveBitVector_1_1NaiveBitVectorIterator.html", null ],
    [ "stool::NaiveDynamicString", "classstool_1_1NaiveDynamicString.html", null ],
    [ "stool::NaiveFLCVector< USE_PSUM >", "classstool_1_1NaiveFLCVector.html", null ],
    [ "stool::NaiveFLCVector< USE_PSUM >::NaiveFLCVectorIterator", "classstool_1_1NaiveFLCVector_1_1NaiveFLCVectorIterator.html", null ],
    [ "stool::NaiveVLCArray< MAX_SEQUENCE_LENGTH >", "classstool_1_1NaiveVLCArray.html", null ],
    [ "stool::OnlineFileReader", "classstool_1_1OnlineFileReader.html", null ],
    [ "stool::OnlineFileReader::OnlineFileReaderIterator", "classstool_1_1OnlineFileReader_1_1OnlineFileReaderIterator.html", null ],
    [ "stool::PackedPsum", "classstool_1_1PackedPsum.html", null ],
    [ "stool::Printer", "classstool_1_1Printer.html", null ],
    [ "stool::rlbwt2::RankSupportVectorWrapper< T >", "classstool_1_1rlbwt2_1_1RankSupportVectorWrapper.html", null ],
    [ "stool::Rational", "structstool_1_1Rational.html", null ],
    [ "stool::rlbwt2::RLE< CHAR >", "classstool_1_1rlbwt2_1_1RLE.html", null ],
    [ "stool::RLEIO", "classstool_1_1RLEIO.html", null ],
    [ "stool::RMQSmallSparseTable< T >", "classstool_1_1RMQSmallSparseTable.html", null ],
    [ "stool::RMQSparseTable< T >", "classstool_1_1RMQSparseTable.html", null ],
    [ "stool::RMQSparseTable< uint64_t >", "classstool_1_1RMQSparseTable.html", null ],
    [ "stool::ShortBitVector", "classstool_1_1ShortBitVector.html", null ],
    [ "stool::ShortEliasFanoVector", "classstool_1_1ShortEliasFanoVector.html", null ],
    [ "stool::ShortIntegerVector", "classstool_1_1ShortIntegerVector.html", null ],
    [ "stool::SIMDFunctions", "classstool_1_1SIMDFunctions.html", null ],
    [ "stool::SimpleDeque< T, INDEX_TYPE >", "classstool_1_1SimpleDeque.html", null ],
    [ "stool::SimpleDeque< uint64_t >", "classstool_1_1SimpleDeque.html", null ],
    [ "stool::SimpleDeque< uint8_t >", "classstool_1_1SimpleDeque.html", null ],
    [ "stool::SimpleDeque< T, INDEX_TYPE >::SimpleDequeIterator", "classstool_1_1SimpleDeque_1_1SimpleDequeIterator.html", null ],
    [ "stool::SimpleSuffixTree", "classstool_1_1SimpleSuffixTree.html", null ],
    [ "stool::SortString", "classstool_1_1SortString.html", null ],
    [ "stool::StaticArrayDeque< SIZE, USE_PSUM_ARRAY >", "classstool_1_1StaticArrayDeque.html", null ],
    [ "stool::StaticArrayDeque< SIZE, false >", "classstool_1_1StaticArrayDeque.html", [
      [ "stool::StaticArrayDeque< SIZE, true >", "classstool_1_1StaticArrayDeque_3_01SIZE_00_01true_01_4.html", null ]
    ] ],
    [ "stool::StaticArrayDeque< SIZE, USE_PSUM_ARRAY >::StaticArrayDequeIterator", "classstool_1_1StaticArrayDeque_1_1StaticArrayDequeIterator.html", null ],
    [ "stool::StringFunctions", "classstool_1_1StringFunctions.html", null ],
    [ "stool::StringFunctionsOnSA", "classstool_1_1StringFunctionsOnSA.html", null ],
    [ "stool::StringGenerator", "classstool_1_1StringGenerator.html", null ],
    [ "stool::SubstringComplexityFunctions", "classstool_1_1SubstringComplexityFunctions.html", null ],
    [ "stool::TextStatistics", "structstool_1_1TextStatistics.html", null ],
    [ "stool::UInt8VectorGenerator", "classstool_1_1UInt8VectorGenerator.html", null ],
    [ "stool::ValueArray", "classstool_1_1ValueArray.html", null ],
    [ "stool::VLCDeque", "classstool_1_1VLCDeque.html", null ],
    [ "stool::rlbwt2::WaveletTreeOnHeadChars", "classstool_1_1rlbwt2_1_1WaveletTreeOnHeadChars.html", null ]
];